### ISSUE TITLE
RingingCallContent vs RingingCallPanel

### ISSUE THREAD

**Issue by aharwood9** [GetStream/stream-video-js#1052]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
I am in the process of trying to add Stream Video to our RN app and trying to use RingingCallContent to display calling and ringing people in the app. The documentation suggests it can take props to customise the UI, however, this seems to be only true of `RingingCallPanel`. Is this a bug or maybe `RingingCallContent` is in the process of being removed? There is very little additional code between them.

**To Reproduce**

1. Use `RingingCallContent` and try to customise the UI
2. See it is not possible

**Expected behavior**
Ability to customise the components within RingingCallContent

**Screenshots**

**Version**

- SDK version 
0.0.4

**Env:**

Fill out what's applicable

**React / JS client**

**React Native**

- OS: [e.g. iOS, linux...]
- Device or emulator [e.g. android emulator, real iPhone X...]

**Node JS client**

- Node version

**Additional context**

**Comment by vishalnarkhede** [comment]
This indeed is a bug, we will fix this immediately.

**Comment by aharwood9** [comment]
Thank you @vishalnarkhede 🚀

**Comment by vishalnarkhede** [comment]
Hey @aharwood9 if possible, could you give us your stream app id? If you are actively integrating video, we could facilitate better communication channel.

**Comment by vishalnarkhede** [comment]
You can share here, not a problem. Or you can give me your email, and we can reach out to you

**Comment by aharwood9** [comment]
I am currently using `1130942` as our staging but I am shortly going to move to our dev one to test notifications on `1125787`. I am looking to switch our janky Twilio setup to GetStream. Got most things setup apart from notifications and custom styling. Do you need any other details?

**Comment by vishalnarkhede** [comment]
Thanks, we will get back to you shortly
