### ISSUE TITLE
Package "@stream-io/video-react-native-sdk" does not contain a valid config plugin.

### ISSUE THREAD

**Issue by fobos531** [GetStream/stream-video-js#1073]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**

I get this error when registering the config plugin

![CleanShot 2023-09-11 at 17 32 43@2x](https://github.com/GetStream/stream-video-js/assets/19533289/575ca208-ea45-44b1-bf8e-ab22b6e86c89)

**To Reproduce**

1. Add `@stream-io/video-react-native-sdk` 0.0.9
2. Register the config plugin
3. Run `npx expo prebuild`

**Expected behavior**
The config plugin should run normally.

**Version**

0.0.9

**React Native**

- OS: macOS
- Device or emulator: N/A

**Comment by fobos531** [comment]
This seems to be working after https://github.com/GetStream/stream-video-js/pull/1075

**Comment by santhoshvai** [comment]
@fobos531 thanks for rasing a bug request!

also thanks for finding that it was fixed 💯
