### ISSUE TITLE
The owner of a call do not automatically cancel the call when Auto-Cancel Timeout reached

### ISSUE THREAD

**Issue by Phu96** [GetStream/stream-video-js#1215]
**Which package/packages do you use?**

- [x ] `@stream-io/video-react-sdk`
- [ ] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
Currently, we're having a problem that when the user makes a ringing call, the logic that automatically cancels the call should be triggered when the Auto-Cancel Timeout config is reached, but in reality it's not.

**To Reproduce**

**Expected behavior**
The logic of automatically cancelling the call when Auto-Cancel Timeout reached should be triggered.

**Screenshots**
![Screenshot from 2023-12-06 17-17-28](https://github.com/GetStream/stream-video-js/assets/30786617/bfdd8fe4-0cb6-426c-8e3e-eb6f182228d2)
I've digged into the source code and saw that when prevTimeoutMs and timeoutMs are the same, it returns and does not run the setTimeout function that triggers the cancel flow. In reality, both prevTimeoutMs and timeoutMs are always the same when the user makes a call, so I am doubting that this is a bug.

**Version**

- SDK version:  @stream-io/video-react-sdk: 0.4.14

**Env:**

Fill out what's applicable

**React / JS client**

- Node version: v18.16.0

**Additional context**
this is the web application built using React JS

**Comment by oliverlaz** [comment]
hi @Phu96, thanks for reporting this issue. We'll take a look at it and get back to you.
