### ISSUE TITLE
react native - default devices are not respected

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-video-js#1219]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
Join a call with

```
await call?.join({
        data: {
          settings_override: {
            audio: {
              default_device: 'speaker',
            },
          },
        },
      });
```

and notice that default device is not respected..

**Comment by vishalnarkhede** [comment]
Hey @santhoshvai please get in touch with support@getstream.io
