### ISSUE TITLE
bug: Unable to resolve "react-native-web/dist/exports/PermissionsAndroid" from "../../node_modules/@stream-io/react-native-webrtc/lib/module/Permissions.js"

### ISSUE THREAD

**Issue by jp4u** [GetStream/stream-video-js#1222]
**Describe the bug**

I installed stream sdk following these directions:

https://getstream.io/video/docs/reactnative/setup/installation/expo/

I am getting this error:

Unable to resolve "react-native-web/dist/exports/PermissionsAndroid" from "../../node_modules/@stream-io/react-native-webrtc/lib/module/Permissions.js"

IOS and Android build fine. But when I try to build web, I get the previous error.

**To Reproduce**

1. Build web

**Expected behavior**

Should allow me to build web as well in a React Native, Expo project

**Comment by santhoshvai** [comment]
Hi, please do not build for web. We do not support the web platform from the React-Native SDK at this point.
