### ISSUE TITLE
Other members automatically join a call when the ringing call has more than two members

### ISSUE THREAD

**Issue by Phu96** [GetStream/stream-video-js#1245]
**Which package/packages do you use?**

- [x ] `@stream-io/video-react-sdk`

**Describe the bug**
When creating a ringing call with more than two members, for instance, the call has four members that are A,B,C,D respectively. The user A is the owner of the call, when the others receive a call notification, and one of them accepts the call, let say the user B accepts the call, then the user C and D will automatically join the call, that is not expected. My expectation is that when the user B accepts the call, only the owner of the call which is the user A will join that call, the others will only join if any of them accepts the call manually.

**To Reproduce**

**Expected behavior**
Only the first user accept the call and the owner will join the call, the others have to accept the call manually to join.

**Screenshots**

**Version**

- SDK version: 0.4.17

**Env:**

Fill out what's applicable

**React / JS client**

**Additional context**

**Comment by oliverlaz** [comment]
hi @Phu96, thanks for reporting this issue. I'll take a look and I'll get back to you.

**Comment by khushal87** [comment]
Hey @Phu96, this issue is fixed on our latest version of SDK - [@stream-io/video-react-sdk-0.4.21](https://github.com/GetStream/stream-video-js/releases/tag/%40stream-io%2Fvideo-react-sdk-0.4.21).

Please try it and let us know how it goes.

Thanks 😄

**Comment by Phu96** [comment]
> Hey @Phu96, this issue is fixed on our latest version of SDK - [@stream-io/video-react-sdk-0.4.21](https://github.com/GetStream/stream-video-js/releases/tag/%40stream-io%2Fvideo-react-sdk-0.4.21).
> 
> Please try it and let us know how it goes.
> 
> Thanks 😄

i've tested and it's working now, thanks 😄
