### ISSUE TITLE
Video call can not share Entire Screen

### ISSUE THREAD

**Issue by vihan85** [GetStream/stream-video-js#1250]
**Which package/packages do you use?**

- [ 0.4.21] `@stream-io/video-react-sdk`
- [ ] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
I can not use the entire screen option

**To Reproduce**
Similar to the attached video

**Expected behavior**

**Screenshots**

https://github.com/GetStream/stream-video-js/assets/104440194/00eed6ec-d95e-442e-92e3-3cc93b5a0768

**Version**

- SDK version

**Env:**

Fill out what's applicable

**React / JS client**

**React Native**

- OS: [e.g. iOS, linux...]
- Device or emulator [e.g. android emulator, real iPhone X...]

**Node JS client**

- Node version

**Additional context**

**Comment by oliverlaz** [comment]
hi @vihan85, thanks for reporting this issue. I think the problem you are experiencing is related to your system-wide permissions for Screen Sharing. While we add the missing notification about this, can you please check if the following settings are enabled on your side?
<img width="705" alt="Screenshot 2024-01-26 at 11 19 25" src="https://github.com/GetStream/stream-video-js/assets/843172/5f62ab1b-279d-4f30-85e6-b9a1892e6b7a">
