### ISSUE TITLE
`Infinity` being passed to participant component internally, crashing app

### ISSUE THREAD

**Issue by cwackerfuss** [GetStream/stream-video-js#1293]
**Which package/packages do you use?**

- [x] `@stream-io/video-react-sdk`
- [ ] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
When initializing a call, the library crashes with this error message:
<img width="371" alt="Screenshot 2024-03-15 at 12 10 26 PM" src="https://github.com/GetStream/stream-video-js/assets/4405356/e71ce72d-42d2-4d94-af62-f245356679f9">

Which originates from this minified source:
<img width="398" alt="Screenshot 2024-03-15 at 12 10 22 PM" src="https://github.com/GetStream/stream-video-js/assets/4405356/4a4a8635-03f4-487d-b87a-2057c6dcdd0e">

When adding a breakpoint, the value `t` passed to the `length` property (highlighted above) is `Infinity`.

This seems like somehow its originating from Stream at a data level and not in the @stream-io/video-react-sdk package, but this felt like the best place to raise the issue

**To Reproduce**
Oddly, I am only able to reproduce this on one of my accounts. I'm also not able to reproduce on https://getstream.io/video/demos

**Expected behavior**
Before yesterday, this worked as expected - could something have changed in the most recent releases 0.5.3 or 0.5.2

**Screenshots**

**Version**

- SDK version
- 0.5.3

**Comment by oliverlaz** [comment]
Hi @cwackerfuss,

Thanks for reporting this issue. I've checked the code, and it seems we aren't guarding ourselves from division by zero properly.
Until we release a fix for this, can you please check whether you use `<PaginatedGridLayout groupSize={0} />`? If yes, please change the value of the `groupSize` to something larger than `0`.

I'll keep you posted once the underlying issue is fixed.

**Comment by cwackerfuss** [comment]
Hi @oliverlaz thanks for the response!

I use `PaginatedGridLayout` via a `useLayoutSwitcher` hook, [copied exactly from the `react-dogfood` repo](https://github.com/GetStream/stream-video-js/blob/main/sample-apps/react/react-dogfood/hooks/useLayoutSwitcher.ts).

**Comment by cwackerfuss** [comment]
Update - while I was copying code from `react-dogfood` I inadvertently changed [this line](https://github.com/GetStream/stream-video-js/blob/main/sample-apps/react/react-dogfood/components/Stage.tsx#L28) to `groupSize={0}` since I'm not using Next. Since it wasn't breaking anything (at first), I didn't go back and fix. Only after I changed to one of the layouts that met the conditions that used the component with 0 being passed did the issue start occurring, and didn't stop occurring due to localstorage caching the layout setting 😅 

Might be good to document this more in case others fall into the same trap, but we can chalk this up to user error.
