### ISSUE TITLE
Camera light stays on after disabling camera (@stream-io/video-react-sdk)

### ISSUE THREAD

**Issue by dawitgem** [GetStream/stream-video-js#1346]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`

**Describe the bug**
I'm having an issue where the camera light remains on even after disabling the camera using the @stream-io/video-react-sdk functions.

**To Reproduce**

Implement functionality to disable the camera stream.
Observe that the camera light remains on despite the stream being disabled.

1.Integrate @stream-io/video-react-sdk into a web application.
2. Implement functionality to disable the camera stream.
3. Observe that the camera light remains on despite the stream being disabled.

**Expected behavior**
The camera light should turn off when the camera stream is disabled using the SDK functions.

**Version**

- 1.0.1

**Env:**

**React / JS client**

- Browser  chrome

**Node JS client**

-20.11.0

**Comment by oliverlaz** [comment]
hi @dawitgem, thanks for reaching out. Could you provide us a Codesandbox (or a repo that reproduces this issue)?
https://codesandbox.io/embed/stream-video-quickstart-y0wo3m is a good start.

**Comment by GuysmoB** [comment]
Hi,

I have the same issue : 
https://codesandbox.io/s/stream-video-quickstart-forked-pz8dsc?file=/src/MeetingSetup.tsx

I can turn on/off the camera light when i do it manually by pressing buttons but if the camera is automatically turn on by the useEffect then i try to turn it off, it doesn't work.

**Comment by oliverlaz** [comment]
hi @GuysmoB, I can't open the linked code sandbox (it appears to be deleted). 
Can you please share a valid link so we can look at it?

**Comment by GuysmoB** [comment]
My bad : https://codesandbox.io/p/sandbox/stream-video-quickstart-forked-pz8dsc?file=%2Fsrc%2FMeetingSetup.tsx

**Comment by oliverlaz** [comment]
hi @GuysmoB, thanks for providing the correct link. I run the CSB and I see the issue.
However, this doesn't seem to appear in the latest version of our SDK (v1.2.15 at this moment):
- https://codesandbox.io/p/sandbox/stream-video-quickstart-forked-df7cgj?file=%2Fsrc%2FMeetingSetup.tsx

Can you please upgrade to the latest SDK version in your app and try again?

**Comment by GuysmoB** [comment]
I thought my SDK version was up to date but it wasn't. 
It works better now, 
Thanks your sir !

**Comment by oliverlaz** [comment]
@GuysmoB you are welcome! 🙌
