### ISSUE TITLE
The label of the screen picture in picture is reversed

### ISSUE THREAD

**Issue by vihan85** [GetStream/stream-video-js#1352]
**Which package/packages do you use?**

-  `@stream-io/video-react-sdk`: ^1.0.1
- [ ] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
The label of the screen picture in picture is reversed

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/GetStream/stream-video-js/assets/104440194/b87af6f0-d0ea-4e75-8797-d6d05c939cfe)

**Version**

- SDK version

**Env:**

Fill out what's applicable

**React / JS client**

**React Native**

- OS: [e.g. iOS, linux...]
- Device or emulator [e.g. android emulator, real iPhone X...]

**Node JS client**

- Node version

**Additional context**

**Comment by oliverlaz** [comment]
Hi, @vihan85, apologies for getting back to you this late.
This is a consequence of us mirroring the local participant's video. Unfortunately, browsers apply these rules to the picture-in-picture element. We can't provide a good fix without making our SDK more complex than necessary, so we will close this issue as "Won't fix".
