### ISSUE TITLE
User role do not impact user capabilities 

### ISSUE THREAD

**Issue by GuysmoB** [GetStream/stream-video-js#1409]
Hi,

When creating a call in React, i add a member with a 'test' role. This role has absolutely none permissions in my dashboard.
But once I joined the call, this user has 25 capabilities allowing him to mute, block the admin.

Do i miss something ?
Thanks for any help !

![image](https://github.com/GetStream/stream-video-js/assets/42407006/58183960-55bb-4cc3-afe9-fcf5d48c9e48)

**Comment by oliverlaz** [comment]
hi @GuysmoB, this shouldn't be the case.

Can you please share your API Key with us so we can check the permissions setup? 
Also, can you tell us what call type you use?

**Comment by GuysmoB** [comment]
Hi @oliverlaz ,

My API key : v6x3d2be4y8x
The call type is default.
![image](https://github.com/GetStream/stream-video-js/assets/42407006/db641db6-f411-4d9a-96c1-8a8793c759ff)

**Comment by oliverlaz** [comment]
hi @GuysmoB, thanks for sharing your API key. I tested myself and I see that user's own capabilities have more than they should.
Can you please raise this issue with our support team? They should be able to pick it up from here:
- https://getstream.io/contact/support/

**Comment by oliverlaz** [comment]
hi @GuysmoB, I'm closing this issue as this request is now handled by our customer support team.

**Comment by GuysmoB** [comment]
Hi @oliverlaz ,

I didn't get any answers from the support team.
Should I open a new ticket ?

Thanks
