### ISSUE TITLE
Help building videocall flow.

### ISSUE THREAD

**Issue by ImamJanjua** [GetStream/stream-video-js#1412]
I know that this might not be the right place for this message, but I don't know where else to ask.

So, I am building a telemedicine app. I want to implement a typical video call flow. I have appointments saved in my backend using Supabase. Now, I want a video call to be created whenever an appointment starts. The patient, who will be using React Native, should be notified. When they enter the app, they should be able to join the call. For the doctor, who is using the web app built with Next.js, there should be an indicator for a call, maybe a top banner or some other notification that tells them there's a call, and they can then join the call. Once they join, the call should continue as normal.

Can I get advice on how to implement this? I looked into the documentation for client and server, but I still can't figure out how to create such a flow.

**Comment by oliverlaz** [comment]
hi @ImamJanjua, can you please reach out to our Support team through the following form?
- https://getstream.io/contact/support/

The team should be able to guide you through the process.

In the meantime, the following sections of our documentation could be a good start:
- https://getstream.io/video/docs/api/calls/
- https://getstream.io/video/docs/reactnative/setup/quickstart/
