### ISSUE TITLE
Using Microphone strea

### ISSUE THREAD

**Issue by Krupskis** [GetStream/stream-video-js#1427]
**Which package/packages do you use?**
- [ ] `@stream-io/video-react-native-sdk`

**Is your feature request related to a problem? Please describe.**
Is microphone stream available for free?

**Comment by oliverlaz** [comment]
hi @Krupskis, I'm not sure if I understand your feature request. Is this something you are looking for?
- https://getstream.io/video/docs/reactnative/core/camera-and-microphone/#access-to-the-microphones-mediastream

**Comment by oliverlaz** [comment]
Closed due to inactivity. @Krupskis please reopen it in case you need anything.
