### ISSUE TITLE
Ringing sound?

### ISSUE THREAD

**Issue by chinesehemp** [GetStream/stream-video-js#1441]
**Which package/packages do you use?**

- [x] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

Is it possible for the client to trigger a ringing sound when a call is ringing?

**Describe the solution you'd like**

Given I have a call,
And I'm using an iPhone 12 Pro,
And I'm using ios 17,
When the ringing panel is open,
Then I hear a ringing sound.

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverlaz** [comment]
hi @chinesehemp, yes this is possible. The SDK signals this trough the `call` object.
Here is a short snippet that you can use to trigger a ringing sound:

```ts
const { useCallingState } = useCallStateHooks();
const callingState = useCallingState();
useEffect(() => {
  if (callingState === CallingState.RINGING) {
    // play ringing sound
  }
  return () => {
    // stop the ringing sound here
  }
}, [callingState]);
```

Please let us know if this helps.
