### ISSUE TITLE
Webhooks events

### ISSUE THREAD

**Issue by GuysmoB** [GetStream/stream-video-js#1478]
Hi,

I'm not sur how to get events from GetStream.
I added the URL in my dashboard :` https://xxxxxxxx/api/webhooks/getStream`
I created my endpoint : 
```
import { headers } from 'next/headers';
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
	try {
		const body = await req.text();
		const signature = headers().get('X-Api-Key') as string;
		const webhookSecret = process.env.NEXT_PUBLIC_STREAM_API_KEY!;
		console.log('webhook');
		console.log('body');
		console.log('signature');

		return NextResponse.json({ result: event, ok: true });
	} catch (error) {
		console.error('Failed to process webhook event', error);
		return NextResponse.json({ message: 'something went wrong', ok: false }, { status: 500 });
	}
}

```

Then i should see any events pushed by getStream ?
My endpoint hasn't been triggered  yet.

Thanks for any hints !

**Comment by szuperaz** [comment]
Hi,

The `stream-video-js` is for client-side integration, if you're having problems with your server-side integration please checkout our [API docs](https://getstream.io/video/docs/api/) which have a [webhook guide](https://getstream.io/video/docs/api/webhooks/overview/#how-to-implement-a-webhook-handler) to see if you missed a step.

Additionally, you can use a tool like https://webhook.site/ that you can set in the Stream dashboard for testing purposes to get an idea about where the error could be in your integration.

If you couldn't find the issue, please contact our [support team](https://getstream.io/contact/support/), and make sure to provide a detailed description of the issue, and your API key as well.

**Comment by GuysmoB** [comment]
Thanks @szuperaz
