### ISSUE TITLE
Expose hook to handle Picture In Picture (PIP)

### ISSUE THREAD

**Issue by Aanu1995** [GetStream/stream-video-js#1481]
**Which package/packages do you use?**

- [x] `@stream-io/video-react-sdk`
- [ ] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Is your feature request related to a problem? Please describe.**
Currently, the picture in picture can only be implemented in the ParticipantViewUISpotlight (Speaker layout), which limits us from activating it automatically when user leaves the video screen or creating a custom button for user to activate it manually.

**Describe the solution you'd like**
I will like a way to handle it with custom button or automatically instead of via ParticipantViewUISpotlight.

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverlaz** [comment]
hi @Aanu1995,

Thanks for raising this issue. I think this behavior can be achieved without any SDK changes. All you should do is to provide your own `ParticipantViewUI` that enhances our SDK-provided one with this extra functionality.

Can you please check if the following solution works for you?
```tsx
import { DefaultParticipantViewUI, useParticipantViewContext } from '@stream-io/video-react-sdk';

const MyParticipantViewUI = () => {
  const { videoElement } = useParticipantViewContext();
  return (
    <>
      <DefaultParticipantViewUI />
      <button onClick={() => videoElement?.requestPictureInPicture()}>
        Enter PiP
      </button>
    </>
  );
};

export const App = () => {
  // ...

  return (
    <SpeakerLayout
      ParticipantViewUIBar={MyParticipantViewUI}
      ParticipantViewUISpotlight={MyParticipantViewUI}
    />
  );
}
```

This way, you'll get access to the `videoElement` of every participant, and you can conditionally `requestPictureInPicture()` to any of them.

You can read more about how this element can be customized in the following docs:
- https://getstream.io/video/docs/react/ui-cookbook/participant-view-customizations/

For convenience, I've prepared a CodeSandbox that you can look at as well:
- https://codesandbox.io/p/sandbox/stream-video-picture-in-picture-3s5fwf

Please let us know if this helps.

**Comment by Aanu1995** [comment]
@oliverlaz Thank you very much. I am already aware of this implementation in the documentation. What I am suggesting is a way to access it outside the Speaker component. The implementation above mentioned that I have to implement it in MyParticipantViewUI component which is then pass to Speaker layout. 

**My request**
A way to implement it outside the Speaker layout

**Comment by oliverlaz** [comment]
hi @Aanu1995, I'm not sure if I understand correctly. Once you get the reference(s) to the `videoElement` you can build a custom logic outside the SpeakerLayout.

Something like this:
```tsx
const refs = new Map<string, Element>();

const MyParticipantViewUI = () => {
  const { videoElement, participant } = useParticipantViewContext();
  useEffect(() => {
    refs.set(participant.sessionId, videoElement);
    return () => { 
      refs.delete(participant.sessionId);
    }
  }, [videoElement, participant]);

  return <DefaultParticipantViewUI />;
};

const App = () => {
  const handle = () => {
     refs.get(participant.sessionId).requestPictureInPicture();
  }
 
 // ...
}
```

**Comment by Aanu1995** [comment]
Thank you. I tried it. It worked in Safari but throws error in Firefox. Seems like permission issue

**Comment by oliverlaz** [comment]
hi @Aanu1995, thanks for getting back to us! I'm glad it works for you.
Regarding the issue with Firefox - it doesn't have support for this feature:
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestPictureInPicture

**Comment by oliverlaz** [comment]
I'll close this issue now. Please re-open it (or open a new one) if you need anything else!
