### ISSUE TITLE
Is there any option for showing caption or subtitle of the video call?

### ISSUE THREAD

**Issue by ShivaAryal** [GetStream/stream-video-js#1534]
**Which package/packages do you use?**

- [x] `@stream-io/video-react-sdk`
- [ ] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverlaz** [comment]
hi @ShivaAryal, we are working on adding first-class support for closed captions in our SDKs.
The feature is almost finished and will be released soon. You can track the progress here: #1508.

I'll close this issue now, as it doesn't describe any bug.
