### ISSUE TITLE
Old tokenProvider called in subsequent connectUser

### ISSUE THREAD

**Issue by IlyaSemenov** [GetStream/stream-video-js#1573]
**Which package/packages do you use?**

- [x] `@stream-io/video-client`

**Describe the bug**
With two `connectUser` calls, if the second call doesn't provide the token provider, the previously provided token provider is used (even for anonymous users!).

**To Reproduce**

```ts
const tokenProvider = async () => {
  console.log("Token provider called")
  return "..."
}
const client = new StreamVideoClient({ apiKey: "..." })
console.log("connectUser")
await client.connectUser({ id: "...." }, tokenProvider)
console.log("disconnectUser")
await client.disconnectUser()
console.log("connectUser(anonymous)")
await client.connectUser({ type: "anonymous" }) // No token provider for anonymous user
```

Result:

```
connectUser
Token provider called
disconnectUser
connectUser(anonymous)
Token provider called
```

**Expected behavior**

In second `connectUser` call, token provider should not be called:
- it's not provided
- it's anonymous user anyway!

In my app, token provider depends on the currently logged user, and if user logs out, it can't generate a token. I expect `client.connectUser` to respect that there is no token provider passed.

**Version**

+ `@stream-io/video-client` 1.10.5 (also was happening on 1.6.0)

**Env:**

- Chrome

**Additional context**

I'm using `@stream-io/video-client` in a SPA and thus must disconnect/reconnect with the streaming sdk when user logs in/logs out.

**Comment by oliverlaz** [comment]
hi @IlyaSemenov, thanks for reporting this issue. We'll take a look at it and we'll get back to you.
