### ISSUE TITLE
Error building on Android while trying to install on Expo 52: Unable to resolve "@notifee/react-native" from "node_modules/@stream-io/video-react-native-sdk/src/utils/push/ios.ts"

### ISSUE THREAD

**Issue by jadk97** [GetStream/stream-video-js#1620]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
Trying to install the latest version of `@stream-io/video-react-native-sdk` (1.4.15), [using the instructions in the docs](https://getstream.io/video/docs/react-native/setup/installation/expo/) results in the following error:
`Unable to resolve "@notifee/react-native" from "node_modules/@stream-io/video-react-native-sdk/src/utils/push/ios.ts"`

**To Reproduce**
1. Run the following
```
npx expo install @stream-io/video-react-native-sdk
npx expo install @stream-io/react-native-webrtc
npx expo install @config-plugins/react-native-webrtc
npx expo install react-native-incall-manager
npx expo install react-native-svg
npx expo install @react-native-community/netinfo

```
2. Add this to the `plugins` array in the app.json/app.config.js in the root directory of your Expo project
```
  plugins: [
    [
      "expo-build-properties",
      {
        android: {
          extraMavenRepos: [
            "$rootDir/../../../node_modules/@notifee/react-native/android/libs",
          ],
          compileSdkVersion: 35,
          targetSdkVersion: 34,
          buildToolsVersion: "34.0.0",
          minSdkVersion: 34,
        },
        ios: {
          deploymentTarget: "15.1",
        },
      },
    ],
      "@stream-io/video-react-native-sdk",
    [
      "@config-plugins/react-native-webrtc",
      {
        cameraPermission: "Allow app to access your camera",
        microphonePermission: "Allow app to access your microphone",
      },
    ]
]
```
4. Run `npx expo prebuild --clean`
5. Run `npm run android`
6. Error `Unable to resolve "@notifee/react-native" from "node_modules/@stream-io/video-react-native-sdk/src/utils/push/ios.ts"` appears immediately after the Android build is finished

**React Native**

- OS: MacOS Sequoia 15.1.1 
- Physical Android device: Samsung S22+ running Android 14
- Expo 52
- React-Native 0.76.3

**Node JS client**
- Node 18

**Comment by tvuquoc17a** [comment]
Face same issue but not expo, can u fix this ?
