### ISSUE TITLE
Could it work with react-native/expo project ?

### ISSUE THREAD

**Issue by adnaneghalem** [GetStream/stream-video-js#859]
I would be really interested in implementing in a react-native/expo project, would it be a nice idea ?

**Comment by khushal87** [comment]
Hey @adnaneghalem we haven't tried it with an expo environment yet but it is in our pipeline to soon create and try the SDK with the expo environment. We will let you know once it's done soon.

Happy to address your questions and requirements. 😄

**Comment by khushal87** [comment]
Hey @adnaneghalem,

We have added Expo support in the latest version [0.0.8](https://github.com/GetStream/stream-video-js/releases/tag/%40stream-io%2Fvideo-react-native-sdk-0.0.8) of Video RN SDK :tada:
Installation Docs for Expo - https://getstream.io/video/docs/reactnative/setup/installation/expo/
Expo sample app - https://github.com/GetStream/stream-video-js/tree/main/sample-apps/react-native/expo-video-sample

P.S. Docs for push notifications on the expo are WIP and will be ready by mid-next week. But that shouldn’t be a blocker for you to integrate. :smile:

Please feel free to reach out if you have any more questions or face any issues while integrating it. I will be closing this issue until then. Thanks 😄
