### ISSUE TITLE
Creating StreamVideoClient triggers a "Chat is not enabled" error

### ISSUE THREAD

**Issue by wooliet** [GetStream/stream-video-js#890]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [ ] `@stream-io/video-react-native-sdk`
- [x] `@stream-io/video-client`

**Describe the bug**

On creating a new `StreamVideoClient` instance, the following error is logged:

>Chat is not enabled for your account, your trial is either expired or not activated. Check https://getstream.io/pricing/chat/ or reach out to support

![image](https://github.com/GetStream/stream-video-js/assets/1421908/9672d48c-0123-4fe1-9ec1-ef1ed4ee1e1e)

The message is correct in that the Chat product is _not_ activated. However, the "Video & Audio" product _is_ activated with a valid key.

**To Reproduce**

Create a new instance of StreamVideoClient using valid token and user id.

```javascript
const videoClient = new StreamVideoClient({
  apiKey: API_KEY,
  token: TOKEN,
  user: {
    id: 'useraaa',
    name: 'User AAA'
  }
});
```

A set of errors is logged to the console:

<img width="926" alt="image" src="https://github.com/GetStream/stream-video-js/assets/1421908/c449cd8e-f350-4038-9e57-a9c43f0c296c">

The `StreamVideoClient` instance is created, and a `Call` is created.  But using it to `join` throws an error, and the error itself is undefined.

```javascript
const videoCall = videoClient.call('default', VIDEO_ID);

try {
  await videoCall.join({ create:true });
}
catch (err) {
  // `err` is undefined
}
```

**Expected behavior**
Expected a new `StreamVideoClient` instance that could be used to create a `Call` and then create a video.

**Screenshots**
Included above

**Version**

- _@stream-io/video-client_: **0.1.9**

**Env:**

Fill out what's applicable

**React / JS client**

- Browser: **chrome**

**Node JS client**

- Node version:  **v18.16.0**

**Additional context**

This is a web application built using Vue.

**Comment by szuperaz** [comment]
Thanks for reporting this. We're looking into it and get back to you shortly.

**Comment by szuperaz** [comment]
Please provide your API key via our support system: https://getstream.io/contact/support/

**Comment by wooliet** [comment]
The solution to my problem was an extension of the Chat trial (not Video). Seems like something that needs sorting out, but for now my issue has been resolved. 

Thanks @szuperaz
